use strum_macros::EnumIter;

#[derive(EnumIter, PartialEq, Clone)]
pub enum Emoji {
    ThumbsUp,
    ThumbsDown,
    Heart,
    Clap,
    Fire,
    Laugh,
    Sad,
    Suprise,
    Grinning,
    GrinningBigEyes,
    GrinningSmilingEyes,
    BeamingSmilingEyes,
    GrinningSquinting,
    GrinningWithSweat,
    Rofl,
    SlightSmile,
    UpsideDown,
    Melting,
    Winking,
    Blushing,
    Angel,
    SmileWithHearts,
    SmileHeartEyes,
    SmileStarEyes,
    BlowingKiss,
    Kissing,
    KissingClosedEyes,
    KissingSmileEyes,
    SmilingWithTear,
    SavoringFood,
    FaceWithTongue,
    WinkingTongue,
    Zany,
    SquintingWithTongue,
    MoneyMouth,
    SmilingWithHands,
    HandOverMouth,
    HandOverMouthOpenEyes,
    PeakingEye,
    Shush,
    Thinking,
    Salute,
    ZipperMouth,
    RaisedEyebrow,
    Neutral,
    Expressionless,
    WithoutMouth,
    DottedLine,
    Smirk,
    Unamused,
    RollingEyes,
    Grimacing,
    Lying,
    Shaking,
    Relieved,
    Pensive,
    Sleepy,
    Drooling,
    Sleeping,
    Mask,
    Thermometer,
    HeadBandage,
    Nauseated,
    Vomiting,
    Sneezing,
    Hot,
    Cold,
    Woozy,
    CrossedOutEyes,
    ExplodingHead,
    Cowboy,
    Party,
    Disguised,
    Sunglasses,
    Nerd,
    Monocle,
    Confused,
    DiagonalMouth,
    Worried,
    SlightFrown,
    OpenMouth,
    Hushed,
    Flushed,
    Pleading,
    HoldingBackTears,
    FrownOpenMouth,
    Anguished,
    Fearful,
    Anxious,
    SadRelieved,
    CryingLoud,
    Screaming,
    Confounded,
    Preserving,
    Disapointed,
    Downcast,
    Weary,
    Tired,
    Yawning,
    SteamFromNose,
    Angry,
    Enraged,
    Cursing,
    SmilingDevil,
    AngryDevil,
    Skull,
    Crossbones,
    Poop,
    Clown,
    Hundred,
    Zzz,
    OkHand,
    PinchedHand,
    PeaceHand,
    CrossedHand,
    IlyHand,
    RockonHand,
    CallmeHand,
    HeartHand,
    PrayerHand,
    Flex,
}

impl Emoji {
    pub const fn as_str(&self) -> &'static str {
        match self {
            Self::ThumbsUp => "\u{1F44D}",
            Self::ThumbsDown => "\u{1F44E}",
            Self::Heart => "\u{2764}\u{FE0F}",
            Self::Clap => "\u{1F44F}",
            Self::Fire => "\u{1F525}",
            Self::Laugh => "\u{1F602}",
            Self::Sad => "\u{1F622}",
            Self::Suprise => "\u{1F632}",
            Self::Grinning => "\u{1F600}",
            Self::GrinningBigEyes => "\u{1F603}",
            Self::GrinningSmilingEyes => "\u{1F604}",
            Self::BeamingSmilingEyes => "\u{1F601}",
            Self::GrinningSquinting => "\u{1F606}",
            Self::GrinningWithSweat => "\u{1F605}",
            Self::Rofl => "\u{1F923}",
            Self::SlightSmile => "\u{1F642}",
            Self::UpsideDown => "\u{1F643}",
            Self::Melting => "\u{1FAE0}",
            Self::Winking => "\u{1F609}",
            Self::Blushing => "\u{1F60A}",
            Self::Angel => "\u{1F607}",
            Self::SmileWithHearts => "\u{1F970}",
            Self::SmileHeartEyes => "\u{1F60D}",
            Self::SmileStarEyes => "\u{1F929}",
            Self::BlowingKiss => "\u{1F618}",
            Self::Kissing => "\u{1F617}",
            Self::KissingClosedEyes => "\u{1F61A}",
            Self::KissingSmileEyes => "\u{1F619}",
            Self::SmilingWithTear => "\u{1F972}",
            Self::SavoringFood => "\u{1F60B}",
            Self::FaceWithTongue => "\u{1F61B}",
            Self::WinkingTongue => "\u{1F61C}",
            Self::Zany => "\u{1F92A}",
            Self::SquintingWithTongue => "\u{1F61D}",
            Self::MoneyMouth => "\u{1F911}",
            Self::SmilingWithHands => "\u{1F917}",
            Self::HandOverMouth => "\u{1F92D}",
            Self::HandOverMouthOpenEyes => "\u{1FAE2}",
            Self::PeakingEye => "\u{1FAE3}",
            Self::Shush => "\u{1F92B}",
            Self::Thinking => "\u{1F914}",
            Self::Salute => "\u{1FAE1}",
            Self::ZipperMouth => "\u{1F910}",
            Self::RaisedEyebrow => "\u{1F928}",
            Self::Neutral => "\u{1F610}",
            Self::Expressionless => "\u{1F611}",
            Self::WithoutMouth => "\u{1F636}",
            Self::DottedLine => "\u{1FAE5}",
            Self::Smirk => "\u{1F60F}",
            Self::Unamused => "\u{1F612}",
            Self::RollingEyes => "\u{1F644}",
            Self::Grimacing => "\u{1F62C}",
            Self::Lying => "\u{1F925}",
            Self::Shaking => "\u{1FAE8}",
            Self::Relieved => "\u{1F60C}",
            Self::Pensive => "\u{1F614}",
            Self::Sleepy => "\u{1F62A}",
            Self::Drooling => "\u{1F924}",
            Self::Sleeping => "\u{1F634}",
            Self::Mask => "\u{1F637}",
            Self::Thermometer => "\u{1F912}",
            Self::HeadBandage => "\u{1F915}",
            Self::Nauseated => "\u{1F922}",
            Self::Vomiting => "\u{1F92E}",
            Self::Sneezing => "\u{1F927}",
            Self::Hot => "\u{1F975}",
            Self::Cold => "\u{1F976}",
            Self::Woozy => "\u{1F974}",
            Self::CrossedOutEyes => "\u{1F635}",
            Self::ExplodingHead => "\u{1F92F}",
            Self::Cowboy => "\u{1F920}",
            Self::Party => "\u{1F973}",
            Self::Disguised => "\u{1F978}",
            Self::Sunglasses => "\u{1F60E}",
            Self::Nerd => "\u{1F913}",
            Self::Monocle => "\u{1F9D0}",
            Self::Confused => "\u{1F615}",
            Self::DiagonalMouth => "\u{1FAE4}",
            Self::Worried => "\u{1F61F}",
            Self::SlightFrown => "\u{1F641}",
            Self::OpenMouth => "\u{1F62E}",
            Self::Hushed => "\u{1F62F}",
            Self::Flushed => "\u{1F633}",
            Self::Pleading => "\u{1F97A}",
            Self::HoldingBackTears => "\u{1F979}",
            Self::FrownOpenMouth => "\u{1F626}",
            Self::Anguished => "\u{1F627}",
            Self::Fearful => "\u{1F628}",
            Self::Anxious => "\u{1F630}",
            Self::SadRelieved => "\u{1F625}",
            Self::CryingLoud => "\u{1F62D}",
            Self::Screaming => "\u{1F631}",
            Self::Confounded => "\u{1F616}",
            Self::Preserving => "\u{1F623}",
            Self::Disapointed => "\u{1F61E}",
            Self::Downcast => "\u{1F613}",
            Self::Weary => "\u{1F629}",
            Self::Tired => "\u{1F62B}",
            Self::Yawning => "\u{1F971}",
            Self::SteamFromNose => "\u{1F624}",
            Self::Angry => "\u{1F620}",
            Self::Enraged => "\u{1F621}",
            Self::Cursing => "\u{1F92C}",
            Self::SmilingDevil => "\u{1F608}",
            Self::AngryDevil => "\u{1F47F}",
            Self::Skull => "\u{1F480}",
            Self::Crossbones => "\u{2620}",
            Self::Poop => "\u{1F4A9}",
            Self::Clown => "\u{1F921}",
            Self::Hundred => "\u{1F4AF}",
            Self::Zzz => "\u{1F4A4}",
            Self::OkHand => "\u{1F44C}",
            Self::PinchedHand => "\u{1F90C}",
            Self::PeaceHand => "\u{270C}",
            Self::CrossedHand => "\u{1F91E}",
            Self::IlyHand => "\u{1F91F}",
            Self::RockonHand => "\u{1F918}",
            Self::CallmeHand => "\u{1F919}",
            Self::HeartHand => "\u{1FAF6}",
            Self::PrayerHand => "\u{1F64F}",
            Self::Flex => "\u{1F4AA}",
        }
    }
}
